import { MessageSquare, ShieldCheck, Share2, AtSign, Layers, Sparkles, Link2, ShoppingBag, Brain, BookOpen, MessageCircle, BarChart3, Code, DollarSign } from "lucide-react";

export const FEATURE_CONFIGS = {
  "comment-to-dm": {
    title: "Comment-to-DM",
    description: "Automatically sends DMs when users comment on posts with matching keywords.",
    codeStatus: "live",
    featureFlag: null,
    stats: [
      { key: "totalEvents", label: "Total triggers", icon: MessageSquare },
      { key: "sent", label: "DMs sent", icon: MessageSquare },
      { key: "eventsToday", label: "Today", icon: MessageSquare },
      { key: "successRate", label: "Success rate", icon: ShieldCheck, format: "percentage" },
    ],
    accountStatColumn: { key: "dmsSentThisMonth", label: "DMs/mo" },
  },
  "follower-gate": {
    title: "Follower gate",
    description: "Requires users to follow before receiving automated DM responses.",
    codeStatus: "live",
    featureFlag: null,
    stats: [
      { key: "totalEvents", label: "Gate checks", icon: ShieldCheck },
      { key: "sent", label: "Passed", icon: ShieldCheck },
      { key: "eventsToday", label: "Today", icon: ShieldCheck },
    ],
  },
  "reel-share": {
    title: "Reel share replies",
    description: "Auto-replies when someone shares your reel or post in DMs.",
    codeStatus: "live",
    featureFlag: null,
    stats: [
      { key: "totalEvents", label: "Reel shares", icon: Share2 },
      { key: "sent", label: "Replies sent", icon: Share2 },
      { key: "eventsToday", label: "Today", icon: Share2 },
      { key: "successRate", label: "Success rate", icon: ShieldCheck, format: "percentage" },
    ],
  },
  "mentions": {
    title: "Mention detection",
    description: "Detects when users mention your account and sends automated replies.",
    codeStatus: "live",
    featureFlag: null,
    stats: [
      { key: "totalEvents", label: "Mentions", icon: AtSign },
      { key: "sent", label: "Replies sent", icon: AtSign },
      { key: "eventsToday", label: "Today", icon: AtSign },
    ],
  },
  "reel-rules": {
    title: "Smart reel rules",
    description: "Category-based reply rules for reel shares using keywords, hashtags, and account matching.",
    codeStatus: "live",
    featureFlag: null,
    stats: [
      { key: "totalEvents", label: "Rule matches", icon: Layers },
      { key: "sent", label: "Replies sent", icon: Layers },
      { key: "eventsToday", label: "Today", icon: Layers },
    ],
  },
  "ai-detection": {
    title: "AI product detection",
    description: "AI vision analyzes shared reels to identify products and send purchase links.",
    codeTag: "[AI DETECTION]",
    codeStatus: "disabled",
    roadmapDate: "Q2 2026",
    featureFlag: "aiProductDetectionUnlocked",
    stats: [
      { key: "totalEvents", label: "Detections", icon: Sparkles },
      { key: "sent", label: "Links sent", icon: Sparkles },
      { key: "enabledUsers", label: "Enabled users", icon: Sparkles },
    ],
    accountStatColumn: { key: "aiDetectionsTotal", label: "Detections" },
  },
  "smart-links": {
    title: "Smart link tracking",
    description: "Tracked redirect URLs for all product links with click analytics.",
    codeTag: "[AI DETECTION]",
    codeStatus: "disabled",
    roadmapDate: "Q2 2026",
    featureFlag: "aiProductDetectionUnlocked",
    stats: [
      { key: "totalEvents", label: "Links created", icon: Link2 },
      { key: "eventsToday", label: "Clicks today", icon: Link2 },
      { key: "enabledUsers", label: "Enabled users", icon: Link2 },
    ],
  },
  "shopify": {
    title: "Shopify integration",
    description: "OAuth connection to Shopify stores with product catalog sync.",
    codeTag: "[SMART FEATURES]",
    codeStatus: "disabled",
    roadmapDate: "Q2 2026",
    featureFlag: "shopifyEnabled",
    stats: [
      { key: "enabledUsers", label: "Stores connected", icon: ShoppingBag },
      { key: "totalEvents", label: "Products synced", icon: ShoppingBag },
    ],
  },
  "smart-replies": {
    title: "AI smart replies",
    description: "AI-powered DM responses grounded in Shopify products and knowledge base.",
    codeTag: "[SMART FEATURES]",
    codeStatus: "disabled",
    roadmapDate: "Q3 2026",
    featureFlag: "smartRepliesEnabled",
    stats: [
      { key: "totalEvents", label: "Replies sent", icon: Brain },
      { key: "eventsToday", label: "Today", icon: Brain },
      { key: "enabledUsers", label: "Enabled users", icon: Brain },
    ],
  },
  "knowledge-base": {
    title: "Knowledge base",
    description: "PDF and URL document processing with vector embeddings for semantic search.",
    codeTag: "[SMART FEATURES]",
    codeStatus: "disabled",
    roadmapDate: "Q3 2026",
    featureFlag: "knowledgeBaseEnabled",
    stats: [
      { key: "enabledUsers", label: "Enabled users", icon: BookOpen },
      { key: "totalEvents", label: "Documents", icon: BookOpen },
    ],
  },
  "conversations": {
    title: "Conversations",
    description: "Multi-turn conversation thread tracking and management.",
    codeTag: "[SMART FEATURES]",
    codeStatus: "disabled",
    roadmapDate: "Q3 2026",
    featureFlag: "smartRepliesEnabled",
    stats: [
      { key: "totalEvents", label: "Conversations", icon: MessageCircle },
      { key: "eventsToday", label: "Active today", icon: MessageCircle },
      { key: "enabledUsers", label: "Enabled users", icon: MessageCircle },
    ],
  },
  "analytics": {
    title: "Advanced analytics",
    description: "Engagement trends, conversion funnels, and exportable reports.",
    codeStatus: "planned",
    roadmapDate: "Q4 2026",
    featureFlag: null,
    stats: [{ key: "totalEvents", label: "Events tracked", icon: BarChart3 }],
  },
  "api-access": {
    title: "API access",
    description: "RESTful API with key management and webhook forwarding.",
    codeStatus: "planned",
    roadmapDate: "Q4 2026",
    featureFlag: null,
    stats: [{ key: "totalEvents", label: "API calls", icon: Code }],
  },
  "payments": {
    title: "Payments",
    description: "Dodo Payments integration for subscription billing.",
    codeTag: "[PAYMENTS DISABLED]",
    codeStatus: "disabled",
    featureFlag: null,
    stats: [{ key: "totalEvents", label: "Transactions", icon: DollarSign }],
  },
};
